const data = {
  articles: [
    {
      title:
        "'Top conviction call:' Analysts say it's time to get back into oil — and name stocks to buy",
      url: "https://www.cnbc.com/2023/12/12/top-conviction-call-analysts-say-time-to-buy-oil-energy-stocks.html",
      author: "Sanjay Mann",
      description:
        "Energy stocks been laggards for much of this year, and were the only sector not to rise in the hot November rally — but some analysts are still bullish.",
      content:
        'Energy stocks been laggards for much of this year, and were the only sector not to rise in the hot November rally — but some analysts are still bullish. In fact, Louis Navellier, chairman and founder of Navellier & Associates, said energy is his "top conviction call" right now. He predicts that crude oil prices will surge again in the spring as seasonal demand returns. "I think Russia is the big wild card at this moment," he told CNBC\'s " Street Signs Asia " on Friday, adding that much of the uncertainty comes from geopolitical and weather risks. "A very cold winter could disrupt Russian crude oil production and Black Sea ports have been hampered by storms," Navellier said. Furthermore, he said, Russia\'s exports have fallen to a three-month low as a result of "wild weather" in the Caspian Sea. "The proxy war in the Middle East, plus Venezuela\'s threat to seize two-thirds of Guyana are other wild cards that could impact crude oil prices," he added. Navellier likes liquefied petroleum gas shipping company Dorian LPG , refinery PBF Energy , as well as oil and gas companies ConocoPhillips and ExxonMobil . In a Dec. 7 note, Citi noted that global oil and gas prices have deflated almost 30% this year, but also highlighted oil\'s defensive qualities, such as lower debt than the rest of the market. "The sector enters 2024 with just one-third the level of leverage of the broad equity market, a relative advantage that the group has not held since the heady oil price days of 2007/08," it said. Because of that, the oil sector is able to use balance sheet strength to protect shareholder distributions, while other sectors face the prospect of refinancing at a significantly higher cost, Citi noted. Citi named two buy-rated energy companies: British oil and gas firm BP and ConocoPhillips. It said that "there is still more left in the trade" given that its valuation is "two-turns" cheaper than its large-cap U.S. peers. Citi also pointed to its potential for growth — underpinned by its shale business — which can outpace that of its peers by the end of the decade. It said BP\'s appointment of a new CEO looks to be a "potential equity catalyst." BP, in "offering both benchmark exposure and a credible New Energy story ... can attract capital," Citi wrote. JPMorgan, for its part, said in its 2024 commodities outlook that it\'s tactically bullish on oil and gas. "We see value in energy—both oil and gas—though timing an entry and exit will continue to be critical," it said. "Steady demand growth should push prices of key commodities, like oil, higher off current spot levels in 2024, with carry adding further to returns," the bank added. It predicts that demand for oil should keep oil prices at a range of between $80 and $90 per barrel, with Brent peaking in the third quarter of 2024. Brent was around $76 on Monday.',
      urlToImage: "https://c.biztoc.com/p/4e3ce1031de01236/s.webp",
      publishedAt: "2023-12-11 23:56:30",
      id: "1",
    },
    {
      title:
        "'Top conviction call:' Analysts say it's time to get back into oil — and name stocks to buy",
      url: "https://www.cnbc.com/2023/12/12/top-conviction-call-analysts-say-time-to-buy-oil-energy-stocks.html",
      author: "Sanjay Mann",
      description:
        "Energy stocks been laggards for much of this year, and were the only sector not to rise in the hot November rally — but some analysts are still bullish.",
      content:
        'Energy stocks been laggards for much of this year, and were the only sector not to rise in the hot November rally — but some analysts are still bullish. In fact, Louis Navellier, chairman and founder of Navellier & Associates, said energy is his "top conviction call" right now. He predicts that crude oil prices will surge again in the spring as seasonal demand returns. "I think Russia is the big wild card at this moment," he told CNBC\'s " Street Signs Asia " on Friday, adding that much of the uncertainty comes from geopolitical and weather risks. "A very cold winter could disrupt Russian crude oil production and Black Sea ports have been hampered by storms," Navellier said. Furthermore, he said, Russia\'s exports have fallen to a three-month low as a result of "wild weather" in the Caspian Sea. "The proxy war in the Middle East, plus Venezuela\'s threat to seize two-thirds of Guyana are other wild cards that could impact crude oil prices," he added. Navellier likes liquefied petroleum gas shipping company Dorian LPG , refinery PBF Energy , as well as oil and gas companies ConocoPhillips and ExxonMobil . In a Dec. 7 note, Citi noted that global oil and gas prices have deflated almost 30% this year, but also highlighted oil\'s defensive qualities, such as lower debt than the rest of the market. "The sector enters 2024 with just one-third the level of leverage of the broad equity market, a relative advantage that the group has not held since the heady oil price days of 2007/08," it said. Because of that, the oil sector is able to use balance sheet strength to protect shareholder distributions, while other sectors face the prospect of refinancing at a significantly higher cost, Citi noted. Citi named two buy-rated energy companies: British oil and gas firm BP and ConocoPhillips. It said that "there is still more left in the trade" given that its valuation is "two-turns" cheaper than its large-cap U.S. peers. Citi also pointed to its potential for growth — underpinned by its shale business — which can outpace that of its peers by the end of the decade. It said BP\'s appointment of a new CEO looks to be a "potential equity catalyst." BP, in "offering both benchmark exposure and a credible New Energy story ... can attract capital," Citi wrote. JPMorgan, for its part, said in its 2024 commodities outlook that it\'s tactically bullish on oil and gas. "We see value in energy—both oil and gas—though timing an entry and exit will continue to be critical," it said. "Steady demand growth should push prices of key commodities, like oil, higher off current spot levels in 2024, with carry adding further to returns," the bank added. It predicts that demand for oil should keep oil prices at a range of between $80 and $90 per barrel, with Brent peaking in the third quarter of 2024. Brent was around $76 on Monday.',
      urlToImage: "https://c.biztoc.com/p/4e3ce1031de01236/s.webp",
      publishedAt: "2023-12-11 23:56:30",
      id: "1",
    },
  ],
};

module.exports = data;
